#!/data/data/com.termux/files/usr/bin/sh
set -e
# Automatically added by dh_installalternatives/13.6
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
	if [ -x "/data/data/com.termux/files/usr/bin/update-alternatives" ]; then
		update-alternatives --install /data/data/com.termux/files/usr/bin/which which /data/data/com.termux/files/usr/bin/which.gnu 400 \
			--slave /data/data/com.termux/files/usr/share/man/man1/which.1.gz which.1.gz /data/data/com.termux/files/usr/share/man/man1/which.gnu.1.gz
	fi
fi
# End automatically added section
