#!/data/data/com.termux/files/usr/bin/sh
set -e
case "$1" in
	(configure|abort-upgrade|abort-remove|abort-deconfigure)
	if [ -x "/data/data/com.termux/files/usr/bin/update-alternatives" ]; then
		update-alternatives --install /data/data/com.termux/files/usr/bin/which which /data/data/com.termux/files/usr/bin/which.debianutils 0 \
			--slave /data/data/com.termux/files/usr/share/man/man1/which.1.gz which.1.gz /data/data/com.termux/files/usr/share/man/man1/which.debianutils.1.gz
	fi
	;;

	(*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac
