#!/data/data/com.termux/files/usr/bin/sh
set -e
case "$1" in
	(remove)
	if [ -x "/data/data/com.termux/files/usr/bin/update-alternatives" ]; then
		update-alternatives --remove which /data/data/com.termux/files/usr/bin/which.debianutils
	fi
	;;
esac
